### ISSUE TITLE
Problem in setFrequency

### ISSUE THREAD

**Issue by KP42full** [RobTillaart/PCA9685_RT#2]
Hi,
There is a problem with scalar computation in void PCA9685::setFrequency(uint16_t freq).
uint8_t scaler = 28828 / (freq * 8) - 1;

4096 / 8 = 512
25000000 / 512 = 48828,125
round(25000000 / 512) = 48828 != 28828

greetings KP42full

**Comment by RobTillaart** [comment]
Sorry, your remark is too short to understand the problem in detail.
But I will investigate

**Comment by RobTillaart** [comment]
You are right, good catch, will update today
