### ISSUE TITLE
MODE2_BLINK

### ISSUE THREAD

**Issue by lowenna** [RobTillaart/PCA9685_RT#21]
Just wondering whether you have an example and any reference to MODE2_BLINK which you have a constant defined as 0x20, or bit 5 in the mode 2 register. 

Looking at the datasheet (eg https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf), section 7.3.2, it seems bits 5 through 7 are reserved?

What I'm really after is whether it's possible to offload to the PCA9685 the ability to blink LEDs without software intervention, and the mention of MODE2_BLINK caught my attention.

Thanks,
John.

**Comment by RobTillaart** [comment]
Thanks for the issue.
That is a good question I do not know the answer right away. This library is written as a spin-off of the PCA9635 library, so it might be a copy/paste error. Need to check the most recent datasheet.

**Comment by RobTillaart** [comment]
quick check at NXP
https://www.nxp.com/products/power-management/lighting-driver-and-controller-ics/led-controllers/16-channel-12-bit-pwm-fm-plus-ic-bus-led-controller:PCA9685

The latest datasheet seems to be revision 4 from 16 April 2015 and it does not mention the MODE2_BLINK bit.

So it probably is a copy/paste bug as said before so the issue will be upgraded to bug.
To come back to your initial question, it seems not possible to let the 9685 do the blinking on its own.

Sorry for the inconvenience.

**Comment by lowenna** [comment]
Thanks for the incredibly quick answer! That is a shame, but it's not a problem doing this in software. Great library :)

**Comment by RobTillaart** [comment]
> Thanks for the incredibly quick answer! That is a shame, but it's not a problem doing this in software. Great library :)

Thanks, you're welcome (was working on another issue when this one popped up)

Created a develop branch - 0.5.0 - in which the PCA9685_MODE2_BLINK is removed, build is running

**Comment by RobTillaart** [comment]
Build of the PR is OK, so I will review tomorrow or later and merge it.
If you want to you can already download the develop branch.
