### ISSUE TITLE
digitalWrite not writing

### ISSUE THREAD

**Issue by GavC666** [RobTillaart/PCA9685_RT#4]
Hi Rob,

When trying to use the lib to switch 8 way realy board via PCA9685 the relay's were inactive.
Not sure if im missing something however changing the high & low values in the .cpp file from hex to 4095 & 0 fixed my issue:

```
void PCA9685::digitalWrite(uint8_t channel, uint8_t mode)
{
  if (mode != LOW) setPWM(channel, 4095, 0);
  else setPWM(channel, 0, 4095);
}
```
Great job with your contribution to the arduino world. Many thanks.

Regards

Gavin

**Comment by RobTillaart** [comment]
Thanks Gavin for finding this issue.
Will dive into it right away.

**Comment by RobTillaart** [comment]
4095 = 0x0FFF, so that sets a PWM signal, 
==> ON @ 0  and OFF @ 4095, so there is 1/4096 second that the signal is LOW. 
Probably this time is too small for the relay to switch off, that is why it works.

The value 0x1000 sets bit 12 which is the permanent ON/OFF bit. 
From my head I am under the assumption that the PWM value is ignored, 
so I must check the datasheet to read the details.

----
**update**
the opposite is also true a HIGH pulse of 1/4096 second is too short to switch the relay.

**Comment by RobTillaart** [comment]
From datasheet P.18

![image](https://user-images.githubusercontent.com/462844/99878908-e9466f80-2c08-11eb-9738-790b8c4bf066.png)

- Example 3: LEDn_ON[12] = 1; LEDn_ON[11:0] = 1022; LEDn_OFF[12] = 0; LEDn_OFF[11:0] = don’t care
- Example 4: LEDn_ON[12] = 0; LEDn_OFF[12] = 0; LEDn_ON[11:0] = LEDn_OFF[11:0]

Can you please try this code (as I have no HW nearby)
```cpp
void PCA9685::digitalWrite(uint8_t channel, uint8_t mode)
{
  if (mode != LOW) setPWM(channel, 0x1000, 0x0000); // example 3, set ON at step 0
  else setPWM(channel, 0x0000, 0x0000);             // example 4 - this is different that the 0.2.2 code indeed a bug
}
```

**Comment by GavC666** [comment]
Hi Rob,

I have tried your suggested code below. Same issue still apparent (Pin never changes from logic low on PCA9685).
0xFFF does work when used instead of 0x1000 (4095vs4096 in decimal).
Also tried decimal 4096 in the code and issue still apparent.
Could it be an overflow error?
Sorry I’m a little out my depth here.

Regards

Gavin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RobTillaart** [comment]
I'm searched my archive and found a PCA9685 board so I hope I can verify the bug soon.

**Comment by RobTillaart** [comment]
- verified the issue 
- created a solution that uses bit[12] of the ON/OFF registers.

```cpp
// datasheet P.18 - fig. 9:  
// Note: bit[11-0] ON should NOT equal timer OFF in ON mode
// in OFF mode it doesn't matter.
void PCA9685::digitalWrite(uint8_t channel, uint8_t mode)
{
  if (mode != LOW) setPWM(channel, 0x1001, 0x0000);
  else setPWM(channel, 0x0000, 0x0000);
}
```

Can you confirm this works?

**Comment by GavC666** [comment]
Hi Rob,

All good with regards to digitalWrite.
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RobTillaart** [comment]
I'll do some tests tomorrow to finalize issue and update the lib.
Thanks for raising the issue and doing tests!

**Comment by GavC666** [comment]
No Worries,

Glad to be of some help after all the help you have provided me via you answers in various forums.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RobTillaart** [comment]
It is not solved yet, wrote a sketch to count the pulses / second 
That should be 0 when set HIGH or LOW. 
- LOW is OK
- HIGH is NOT OK

investigating continues,
